#Comandos
EXIT = "exit"
HELP = "help"
REGISTER = "register"
USERS = "users"
ADDFRIEND = "addfriend"
FRIENDS = "friends"
POST = "post"
USERPOSTS = "userposts"
COMMENT = "comment"
READPOST = "readpost"
COMMENTSBYUSER = "commentsbyuser"
TOPICFANATICS = "topicfanatics"
TOPICPOSTS = "topicposts"

#Mensagens dos comandos 
MSG_REGISTER = "registers a new user"
MSG_USERS = "lists all users"
MSG_ADDFRIEND = "adds a new friend"
MSG_FRIENDS = "lists the user friends"
MSG_POST = "posts a new message"
MSG_USERPOSTS = "lists all posts by a user"
MSG_COMMENT = "user comments on a post"
MSG_READPOST = "prints detailed info on a post"
MSG_COMMENTSBYUSER = "shows all the comments by a user on a given post"
MSG_TOPICFANATICS = "shows a list of fanatic users on a topic"
MSG_TOPICPOSTS = "shows a list of posts on a given topic"
MSG_HELP = "shows the available commands"
MSG_EXIT = "terminates the execution of the program"
MSG_UNKNOWN = "Unknown command. Type help to see available commands."
BYE_MSG = "Bye!"
